name: Our first dbt PR job

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.17'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Navigate to dbt project and check connection
        run: |
          cd models/dbt_project
          dbt debug

      - name: Install dbt dependencies
        run: |
          cd models/dbt_project
          dbt deps

      - name: Run dbt build
        run: |
          cd models/dbt_project
          dbt build  # Add --full-refresh --profiles-dir ./ if needed